-- ==============================================================================
-- ATUALIZACAO SCHEMA CORE: AUDITORIA EM 4 CAMADAS E SESSOES POSTGRESQL (0008)
-- Framework LuftBase / Luft-Workspace
-- ==============================================================================

BEGIN;

-- 1. Refatorar tb_logacesso
ALTER TABLE core.tb_logacesso RENAME COLUMN id_usuario TO codigo_usuario;
ALTER TABLE core.tb_logacesso RENAME COLUMN nome_usuario TO login_usuario;
ALTER TABLE core.tb_logacesso ALTER COLUMN login_usuario TYPE varchar(100);
ALTER TABLE core.tb_logacesso ADD COLUMN IF NOT EXISTS user_agent varchar(500);

-- 2. Refatorar tb_logdetalhe
ALTER TABLE core.tb_logdetalhe RENAME COLUMN id_usuario TO codigo_usuario;
ALTER TABLE core.tb_logdetalhe RENAME COLUMN nome_usuario TO login_usuario;
ALTER TABLE core.tb_logdetalhe ALTER COLUMN login_usuario TYPE varchar(100);

-- 3. Criar core.tb_sessao
CREATE TABLE IF NOT EXISTS core.tb_sessao (
    id_sessao varchar(128) NOT NULL,
    id_sistema integer,
    codigo_usuario integer,
    login_usuario varchar(100),
    ip_origem varchar(50),
    user_agent varchar(500),
    dados_sessao text,
    status varchar(20) DEFAULT 'ATIVA' NOT NULL,
    total_renovacoes integer DEFAULT 0 NOT NULL,
    criada_em timestamp(3) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo') NOT NULL,
    ultima_atividade timestamp(3) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo') NOT NULL,
    expira_em timestamp(3) without time zone NOT NULL,
    encerrada_em timestamp(3) without time zone,
    motivo_encerramento varchar(100),
    CONSTRAINT pk_core_sessao PRIMARY KEY (id_sessao),
    CONSTRAINT fk_core_sessao_sistema FOREIGN KEY (id_sistema) REFERENCES core.tb_sistema (id_sistema),
    CONSTRAINT ck_core_sessao_status CHECK (status IN ('ATIVA', 'FINALIZADA', 'EXPIRADA', 'REVOGADA'))
);

CREATE INDEX IF NOT EXISTS ix_core_sessao_status_expira ON core.tb_sessao (status, expira_em);
CREATE INDEX IF NOT EXISTS ix_core_sessao_usuario ON core.tb_sessao (codigo_usuario);
CREATE INDEX IF NOT EXISTS ix_core_sessao_sistema ON core.tb_sessao (id_sistema);
CREATE INDEX IF NOT EXISTS ix_core_sessao_ultima_atividade ON core.tb_sessao (ultima_atividade DESC);

-- 4. Criar core.tb_sessao_evento
CREATE TABLE IF NOT EXISTS core.tb_sessao_evento (
    id_evento_sessao bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_sessao varchar(128) NOT NULL,
    id_sistema integer,
    codigo_usuario integer,
    login_usuario varchar(100),
    tipo_evento varchar(50) NOT NULL,
    ip_origem varchar(50),
    user_agent varchar(500),
    data_hora timestamp(3) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'America/Sao_Paulo') NOT NULL,
    detalhes text,
    CONSTRAINT pk_core_sessaoevento PRIMARY KEY (id_evento_sessao),
    CONSTRAINT fk_core_sessaoevento_sessao FOREIGN KEY (id_sessao) REFERENCES core.tb_sessao (id_sessao) ON DELETE CASCADE,
    CONSTRAINT fk_core_sessaoevento_sistema FOREIGN KEY (id_sistema) REFERENCES core.tb_sistema (id_sistema),
    CONSTRAINT ck_core_sessaoevento_tipo CHECK (tipo_evento IN ('INICIO', 'RENOVACAO', 'LOGOUT', 'TIMEOUT', 'REVOGACAO'))
);

CREATE INDEX IF NOT EXISTS ix_core_sessaoevento_sessao ON core.tb_sessao_evento (id_sessao);
CREATE INDEX IF NOT EXISTS ix_core_sessaoevento_usuario_data ON core.tb_sessao_evento (codigo_usuario, data_hora DESC);
CREATE INDEX IF NOT EXISTS ix_core_sessaoevento_data ON core.tb_sessao_evento (data_hora DESC);

-- 5. Privilegios para aplicacoes
GRANT SELECT, INSERT, UPDATE, DELETE ON core.tb_sessao, core.tb_sessao_evento TO
    luft_core_security_admin,
    luft_workspace_app,
    luft_connectair_app,
    luft_control_app,
    luft_docs_app,
    luft_integrador_app;

-- 6. Atualizar versao do Alembic
UPDATE core.alembic_version
SET version_num = '20260918_0008'
WHERE version_num = '20260917_0007';

COMMIT;

